version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: qasir-profile-website
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules